services:
  frontend:
    image: ghcr.io/profiidev/images/node-alpine-dev:main
    volumes:
      - ./frontend:/app/frontend
      - ./node_modules:/app/node_modules
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
    tty: true
    ports:
      - '1420:1420'
    command: npm run dev -- --host
